### ISSUE TITLE
Avançar o PWA para que o app funcione offline

### ISSUE THREAD

**Issue by lucaslgr** [querocriarsite/coronavirus#1]
O que você acha de evoluir as funcionalidades PWA do app para que ele possa ser consultado também offline?

**Comment by querocriarsite** [comment]
> O que você acha de evoluir como funcionalidades O PWA do aplicativo para que possa ser consultado também offline?

Excelente ideia, não tinha pensado nisso ainda, vai ser de grande ajuda se puder contribuir!
